// Command event-service is the composition root: the only file that imports
// every layer and wires concrete adapters into the domain ports, plus the
// process lifecycle (startup, graceful shutdown). No business logic here.
package main

import (
	"context"
	"errors"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	httpadapter "github.com/buixuankhai1204/ticket-microservice-golang/services/event-service/internal/adapter/http"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/event-service/internal/adapter/repository/postgres"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/event-service/internal/platform/config"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/event-service/internal/platform/db"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/event-service/internal/platform/logger"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/event-service/internal/usecase"

	// Generated by `swag init -g cmd/main.go -o docs`; blank-imported so its
	// init() registers the spec that /swagger/ serves.
	_ "github.com/buixuankhai1204/ticket-microservice-golang/services/event-service/docs"
)

//	@title			event-service API
//	@version		1.0
//	@description	Read side of the event catalogue: browse events and their seat maps.
//	@BasePath		/api/v1

func main() {
	log := logger.New()
	if err := run(log); err != nil {
		log.Error("fatal", "err", err.Error())
		os.Exit(1)
	}
}

func run(log logger.Logger) error {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	cfg, err := config.Load()
	if err != nil {
		return err
	}

	pool, err := db.NewPool(ctx, cfg.DatabaseURL, cfg.DBMaxConns)
	if err != nil {
		return err
	}
	defer pool.Close()

	if err := db.Migrate(ctx, pool); err != nil {
		return err
	}

	// --- composition root: concrete adapters -> domain ports ---
	repo := postgres.New(pool)
	listEvents := usecase.NewListEventsUseCase(repo)
	getEvent := usecase.NewGetEventUseCase(repo)
	listEventSeats := usecase.NewListEventSeatsUseCase(repo)

	handler := httpadapter.NewHandler(listEvents, getEvent, listEventSeats)
	health := httpadapter.NewHealthHandler(pool)
	router := httpadapter.NewRouter(handler, health,
		httpadapter.RequestID(),
		httpadapter.AccessLog(log),
	)

	srv := &http.Server{
		Addr:              ":" + strconv.Itoa(cfg.Port),
		Handler:           router,
		ReadHeaderTimeout: 5 * time.Second,
	}

	serverErr := make(chan error, 1)
	go func() {
		log.Info("event-service listening", "port", cfg.Port)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
		}
	}()

	select {
	case err := <-serverErr:
		return err
	case <-ctx.Done():
		log.Info("shutdown signal received, draining in-flight requests")
	}

	shutdownCtx, cancel := context.WithTimeout(context.Background(), cfg.ShutdownGrace)
	defer cancel()
	return srv.Shutdown(shutdownCtx)
}
