package http

import (
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger"
)

// NewRouter wires every route for the service. Prefixes must match
// kong/kong.yml exactly: Kong routes this service with strip_path: false, so it
// receives the full /api/v1/events path and must NOT strip the prefix. The
// /api/v1/events route has no jwt plugin in kong.yml — event browsing is public.
func NewRouter(h *Handler, health *HealthHandler, mw ...Middleware) http.Handler {
	mux := http.NewServeMux()

	// Infra probes (not under the gateway prefix, not rate-limited).
	mux.HandleFunc("GET /healthz", health.Live)
	mux.HandleFunc("GET /readyz", health.Ready)

	// Interactive API docs generated by swaggo (`swag init`). Served straight
	// off this service, independent of the repo-level docs/openapi bundle.
	mux.Handle("GET /swagger/", httpSwagger.WrapHandler)

	// Client-facing routes, full /api/v1/events prefix retained.
	mux.HandleFunc("GET /api/v1/events", h.ListEvents)
	mux.HandleFunc("POST /api/v1/events", h.CreateEvent)
	mux.HandleFunc("GET /api/v1/events/{eventID}", h.GetEvent)
	mux.HandleFunc("GET /api/v1/events/{eventID}/seats", h.ListEventSeats)

	return Chain(mux, mw...)
}
