// Command analytics-service is the composition root: the only file that imports
// every layer and wires concrete adapters into the domain ports, plus the
// process lifecycle (startup, graceful shutdown). No business logic here.
package main

import (
	"context"
	"errors"
	"net/http"
	"os"
	"os/signal"
	"strconv"
	"syscall"
	"time"

	httpadapter "github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/internal/adapter/http"
	kafkaconsumer "github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/internal/adapter/messaging/kafka"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/internal/adapter/repository/postgres"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/internal/platform/config"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/internal/platform/db"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/internal/platform/logger"
	"github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/internal/usecase"

	// Generated by `swag init -g cmd/main.go -o docs`; blank-imported so its
	// init() registers the spec that /swagger/ serves.
	_ "github.com/buixuankhai1204/ticket-microservice-golang/services/analytics-service/docs"
)

//	@title						analytics-service API
//	@version					1.0
//	@description				Read-only projections built from saga events (user registrations, event booking stats).
//	@BasePath					/api/v1
//	@securityDefinitions.apikey	BearerAuth
//	@in							header
//	@name						Authorization

func main() {
	log := logger.New()
	if err := run(log); err != nil {
		log.Error("fatal", "err", err.Error())
		os.Exit(1)
	}
}

func run(log logger.Logger) error {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	cfg, err := config.Load()
	if err != nil {
		return err
	}

	pool, err := db.NewPool(ctx, cfg.DatabaseURL, cfg.DBMaxConns)
	if err != nil {
		return err
	}
	defer pool.Close()

	if err := db.Migrate(ctx, pool); err != nil {
		return err
	}

	// --- composition root: concrete adapters -> domain ports ---
	repo := postgres.New(pool)
	getEventStats := usecase.NewGetEventStatsUseCase(repo)
	getUserRegistration := usecase.NewGetUserRegistrationUseCase(repo)
	recordUserRegistration := usecase.NewRecordUserRegistrationUseCase(repo)

	handler := httpadapter.NewHandler(getEventStats, getUserRegistration)
	health := httpadapter.NewHealthHandler(pool)
	router := httpadapter.NewRouter(handler, health,
		httpadapter.RequestID(),
		httpadapter.AccessLog(log),
	)

	srv := &http.Server{
		Addr:              ":" + strconv.Itoa(cfg.Port),
		Handler:           router,
		ReadHeaderTimeout: 5 * time.Second,
	}

	// Inbound saga adapter: consume UserCreated from user-service and project it
	// into the read model. Stops on the same ctx as the HTTP server.
	consumer := kafkaconsumer.NewConsumer(kafkaconsumer.Config{
		Brokers:     cfg.KafkaBrokers,
		Topic:       cfg.KafkaUserCreatedTopic,
		MaxAttempts: cfg.KafkaConsumerMaxAttempts,
	}, recordUserRegistration, log)
	defer func() { _ = consumer.Close() }()

	consumerDone := make(chan struct{})
	go func() {
		defer close(consumerDone)
		if err := consumer.Run(ctx); err != nil {
			log.Error("kafka consumer exited with error", "err", err.Error())
		}
	}()

	serverErr := make(chan error, 1)
	go func() {
		log.Info("analytics-service listening", "port", cfg.Port)
		if err := srv.ListenAndServe(); err != nil && !errors.Is(err, http.ErrServerClosed) {
			serverErr <- err
		}
	}()

	select {
	case err := <-serverErr:
		return err
	case <-ctx.Done():
		log.Info("shutdown signal received, draining in-flight requests")
	}

	shutdownCtx, cancel := context.WithTimeout(context.Background(), cfg.ShutdownGrace)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		return err
	}

	// ctx is already cancelled here (that's why we're shutting down), so the
	// consumer is on its way out — wait for it to release the Kafka connection.
	<-consumerDone
	return nil
}
